# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    marketing:
                        password: marketing
                        roles: 'ROLE_MARKETING'
                    fournisseur:
                        password: fournisseur
                        roles: 'ROLE_FOURNISSEUR'
                    achat:
                        password: achat
                        roles: 'ROLE_ACHAT'

    role_hierarchy:
        ROLE_ADMIN: ['ROLE_MARKETING', 'ROLE_FOURNISSEUR', 'ROLE_ACHAT']
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: login
                check_path: login

            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/product, roles: ROLE_FOURNISSEUR }
        - { path: ^/box, roles: ROLE_MARKETING }
        - { path: ^/product, roles: ROLE_ACHAT }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }