framework:
     workflows:
          box_publishing:
              type: 'workflow'
              marking_store:
                  type: 'single_state'
                  arguments:
                      - 'statut'
              supports:
                  - AppBundle\Entity\Box
              places:
                  - draft
                  - review
                  - rejected
                  - published
              transitions:
                  to_review:
                      from: [draft, rejected]
                      to:   review
                  publish:
                      from: review
                      to:   published
                  reject:
                      from: review
                      to:   rejected

          product_publishing:
                type: 'workflow'
                marking_store:
                    type: 'single_state'
                    arguments:
                        - 'statut'
                supports:
                    - AppBundle\Entity\Product
                places:
                    - draft
                    - review
                    - rejected
                    - published
                transitions:
                    to_review:
                        from: [draft, rejected]
                        to:   review
                    publish:
                        from: review
                        to:   published
                    reject:
                        from: review
                        to:   rejected